# Generated by Django 4.2.7 on 2023-11-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriiption',
            new_name='description',
        ),
    ]
